
version: '3.3'

services:

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env-mongo
    ports:
      - 27017:27017  
    volumes:
      - ./mongo-startup-config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env

  node-coinmarketcap-mongo:
    build: ./node-coinmarketcap-mongo
    image: node-coinmarketcap-mongo
    restart: always
    depends_on:
      - mongo-express
    env_file:
      - .env
  
  node-backend-ws-mongo:
    build: ./node-backend-ws-mongo
    image: node-backend-ws-mongo
    restart: always
    depends_on:
      - node-coinmarketcap-mongo
    env_file:
      - .env
    ports:
      - 5500:5500

  angular-frontend:
    build: ./angular-frontend
    image: angular-frontend
    restart: always
    depends_on:
      - node-backend-ws-mongo
    env_file:
      - .env
    ports:
      - 8090:80    

      

